<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.32.4" />


<title>spark_apply: Column must have a unique name - Gray Analytics</title>
<meta property="og:title" content="spark_apply: Column must have a unique name - Gray Analytics">



  








<link href='//cdn.bootcss.com/highlight.js/9.11.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/GrayAnalytics">GitHub</a></li>
    
    <li><a href="https://twitter.com/GrayAnalyst">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">4 min read</span>
    

    <h1 class="article-title">spark_apply: Column must have a unique name</h1>

    
    <span class="article-date">2018/06/04</span>
    

    <div class="article-content">
      

<h1 id="spark-apply-error-column-must-have-a-unique-name">spark_apply():: Error: Column must have a unique name</h1>

<p>Did you get excited learning that spark_apply() will let you run your own custom functions in spark?</p>

<p>And then, no matter what, you&rsquo;re getting this joyous error?</p>

<pre><code>Column '[column name]' must have a unique name.
</code></pre>

<p>There&rsquo;s a few possible causes:</p>

<ul>
<li>You&rsquo;re using the <strong>group_by</strong> parameter, and the column name actually isn&rsquo;t unique.<br /></li>
<li>The function you&rsquo;re running through spark_apply() returns multiple rows/values per input.</li>
</ul>

<p>let&rsquo;s dig in.</p>

<h2 id="1-the-column-name-actually-isn-t-unique">1) The column name actually isn&rsquo;t unique</h2>

<p>When you&rsquo;re using the <strong>group_by</strong> parameter, spark_apply() will return two columns.</p>

<ul>
<li>The group_by column.<br /></li>
<li>The result of the function you ran through spark_apply().<br /></li>
</ul>

<p>But here&rsquo;s the real kicker. The names for these columns?</p>

<ol>
<li>The name of the group_by column,</li>
<li>and the name of the first column in the input dataset.<br /></li>
</ol>

<p>So we see the issue, your <strong>group_by</strong> column is probably the first column of the input dataset.<br />
Let&rsquo;s look at an example.</p>

<pre><code>#input dataset
 dataset &lt;- data.frame(name = c('mark', 'mark', 'mark', 
                                'doug', 'doug', 'doug', 
                                'tiffany', 'tiffany', 'tiffany'), 
                       weight = c(190, 180, 185, 199, 190, 187, 
                                  150, 155, 170))
                                  
 dataset_tbl &lt;- sdf_copy_to(sc, dataset)
 dataset_tbl %&gt;% spark_apply(function, group_by = &quot;name&quot;)
</code></pre>

<p>So we have the dataset.</p>

<table>
<thead>
<tr>
<th>name</th>
<th>weight</th>
</tr>
</thead>

<tbody>
<tr>
<td>mark</td>
<td>190</td>
</tr>

<tr>
<td>mark</td>
<td>180</td>
</tr>

<tr>
<td>mark</td>
<td>185</td>
</tr>

<tr>
<td>doug</td>
<td>199</td>
</tr>

<tr>
<td>doug</td>
<td>190</td>
</tr>

<tr>
<td>doug</td>
<td>187</td>
</tr>

<tr>
<td>tiffany</td>
<td>150</td>
</tr>

<tr>
<td>tiffany</td>
<td>155</td>
</tr>

<tr>
<td>tiffany</td>
<td>170</td>
</tr>
</tbody>
</table>

<p>This is trying to return</p>

<table>
<thead>
<tr>
<th>name</th>
<th>name</th>
</tr>
</thead>

<tbody>
<tr>
<td>mark</td>
<td>(result)</td>
</tr>

<tr>
<td>doug</td>
<td>(result)</td>
</tr>

<tr>
<td>tiffany</td>
<td>(result)</td>
</tr>
</tbody>
</table>

<p>So it&rsquo;s throwing errors because both columns are named <strong>name</strong>. Re-order your columns and it may fix the problem.<br />
So that&rsquo;s cause number one.</p>

<h2 id="2-the-function-you-re-running-through-spark-apply-returns-multiple-rows-values-per-input">2) The function you&rsquo;re running through spark_apply() returns multiple rows/values per input</h2>

<p>spark_apply() wants you to return only one value per input. You know, like a normal apply function. And you&rsquo;re trying to use it like a <strong>tapply()</strong> or <strong>by</strong> function!<br />
 So let&rsquo;s fix that. When your function wants to return a dataframe, we&rsquo;ll just convert it into a LONG string.<br />
 <br>
Think of how a csv file is read. It&rsquo;s essentially a LONG string. But the computer knows that <strong>\n</strong> is used to separate rows, and <strong>,</strong> is used to separate columns. We can do that in reverse.<br />
Back to our example&hellip;</p>

<pre><code>#Function creation
WeightSummary &lt;- function(data){
  current &lt;- tail(data, n=1)
  worst &lt;- head(subset(data, weight == max(data$weight)), n=1)
  current &lt;- rbind(current, worst)
  row.names(current) &lt;- NULL
  return(current)
}
#input dataset
 dataset &lt;- data.frame(weight = c(190, 180, 185, 199, 190, 187, 
                                  150, 155, 170),
                       name = c('mark', 'mark', 'mark', 
                                'doug', 'doug', 'doug', 
                                'tiffany', 'tiffany', 'tiffany'))

</code></pre>

<p>This function returns 2 rows per name.
Now, for each row in <strong>current</strong> we want to concatenate all of the columns together, with a unique separator, something more rare than <strong>,</strong>.</p>

<pre><code>column_collapse &lt;- apply(current[,], 1, function(x) paste(x, collapse = &quot;@@&quot;))
</code></pre>

<p>Excellent, we went from a 2x2 data frame to a List with two elements. (Columns are separated by <strong>@@</strong>)<br />
If you paste a list, it will return a string&hellip;<br />
But we&rsquo;ll need to add an equivalent to <strong>\n</strong>.<br />
<code>
row_collapse &lt;- paste(column_collapse, collapse = &quot;!!&quot;)
</code></p>

<p>Now, let&rsquo;s bring it all together. Our example function should look like&hellip;</p>

<pre><code>## Function creation
WeightSummary &lt;- function(data){
  current &lt;- tail(data, n=1)
  worst &lt;- head(subset(data, weight == max(data$weight)), n=1)
  current &lt;- rbind(current, worst)
  row.names(current) &lt;- NULL
  column_collapse &lt;- apply(current[,], 1, function(x) paste(x, collapse = &quot;@@&quot;))
  row_collapse &lt;- paste(column_collapse, collapse = &quot;!!&quot;)
  return(row_collapse)
}
</code></pre>

<p>Ok, So now, if you run <code>WeightSummary(dataset)</code> then we should see.</p>

<pre><code>170@@tiffany!!199@@doug
</code></pre>

<p>We can see how the two lines are separated by <strong>!!</strong>, also <strong>weight</strong> and <strong>name</strong> are separated by <strong>@@</strong>.<br />
 Let&rsquo;s try this with spark_apply()</p>

<pre><code>dataset_tbl %&gt;% spark_apply(WeightSummary, group_by = &quot;name&quot;)
</code></pre>

<table>
<thead>
<tr>
<th>name</th>
<th>weight</th>
</tr>
</thead>

<tbody>
<tr>
<td>mark</td>
<td>185@@mark!!190@@mark</td>
</tr>

<tr>
<td>doug</td>
<td>187@@doug!!199@@doug</td>
</tr>

<tr>
<td>tiffany</td>
<td>170@@tiffany!!170@@tiffany</td>
</tr>
</tbody>
</table>

<p>And now you&rsquo;re no longer getting those unique column errors!
 But we need to convert these strings back to a dataframe&hellip;
Let&rsquo;s start with mark&rsquo;s value <code>185@@mark!!190@@mark</code>.<br />
Consider running the next two commands</p>

<pre><code>row_decollapse &lt;- unlist(strsplit(row_collapse, split = &quot;!!&quot;, fixed = TRUE))
column_decollapse &lt;- t(data.frame(apply(as.data.frame(row_decollapse), 1, function(x) unlist(strsplit(x, split = &quot;@@&quot;, fixed = TRUE)))))
</code></pre>

<p>This would return</p>

<table>
<thead>
<tr>
<th>row_decollapse1</th>
<th>row_decollapse2</th>
</tr>
</thead>

<tbody>
<tr>
<td>&ldquo;185&rdquo;</td>
<td>&ldquo;mark&rdquo;</td>
</tr>

<tr>
<td>&ldquo;190&rdquo;</td>
<td>&ldquo;mark&rdquo;</td>
</tr>
</tbody>
</table>

<p>Notice that the integers have been changed to strings, and that the column names were lost.</p>

<p>If we were to convert the above code into a function, we could then lapply it to the result column in the output from spark_apply.<br />
Then you&rsquo;re merely an as.data.frame and rbind.fill away from having spark_apply return a dataframe!</p>

<p>Hope that was helpful. Go forth and write bugs no more.</p>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdn.bootcss.com/highlight.js/9.11.0/highlight.min.js"></script>



<script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/r.min.js"></script>
<script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

